eps: 0.001
#eval_mode: False
eval_mode: True

# optimizer
lr: 0.0001
# train

#验证集val复现成功，结果保存在/root/lanyun-tmp/data/DanceTrack/results/val/yolox_m_lt_ddm_1000eps_deeper_800_1rev
#data_dir: '/root/lanyun-tmp/data/DanceTrack/trackers_val'

data_dir: "/root/lanyun-tmp/data/DanceTrack/trackers"
diffnet: HMINet
interval: 5
augment: True
encoder_dim: 256
tf_layer: 3
epochs: 20
batch_size: 2048
seed: 123
eval_every: 20
gpus: [0]

# Testing
eval_at: 800

#验证测试集所用的参数
#det_dir: "/root/lanyun-tmp/data/DanceTrack/detections/val"
#info_dir: "/root/lanyun-tmp/data/DanceTrack/val"
#reid_dir: "/root/lanyun-tmp/experiment/DiffMOT/othertools/DanceTrack/embeddings_yolox_x"
#save_dir: "/root/lanyun-tmp/data/DanceTrack/results/val/yolox_m_lt_ddm_1000eps_deeper_800_1rev"

det_dir: "/root/lanyun-tmp/experiment/DiffMOT/detection_tool"
info_dir: "/root/lanyun-tmp/data/DanceTrack/train"
reid_dir: "/root/lanyun-tmp/experiment/DiffMOT/othertools/DanceTrack/embeddings_yolox_x"
save_dir: "/root/lanyun-tmp/data/DanceTrack/results/train/yolox_m_lt_ddm_1000eps_deeper_800_1rev"
eval_expname: lt_ddm_1000_deeper
high_thres: 0.6
low_thres: 0.4
w_assoc_emb: 2.2
aw_param: 1.7
preprocess_workers: 16

# Data Parameters:
device: cuda
eval_device: None